### PR TITLE
update to 0.3.1

### PR DESCRIPTION
**Pull request by cunidev**

### CODE REVIEW

**Comment by cunidev** [comment]
@barthalion 

Hi, apparently the error has to do with "unnecessary permissions", but Gestures needs to access these two configuration files in the host machine's .config directory. Has anything changed on this side recently?

**Comment by barthalion** [comment]
Please submit a change to https://github.com/flathub/flatpak-builder-lint/blob/master/flatpak_builder_lint/staticfiles/exceptions.json. As this has been accepted during initial review, it should be exempted from the rule.

**Comment by cunidev** [comment]
Thanks! I sent the PR: https://github.com/flathub/flatpak-builder-lint/pull/70

**Comment by cunidev** [comment]
bot, build com.gitlab.cunidev.Gestures

**Pull request merged**
